// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: beacon/sso/v1/auth.proto

package pb

import (
	generate "github.com/bamboo-services/bamboo-base-go/plugins/grpc/generate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterByEmailRequest 邮箱注册请求
type RegisterByEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 邮箱地址（必填）
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// 验证码（必填）
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 用户名（可选，不填则自动生成）
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// 密码（必填，至少 6 位且包含字母和数字）
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// 昵称（可选，不填则使用用户名或自动生成）
	Nickname      string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterByEmailRequest) Reset() {
	*x = RegisterByEmailRequest{}
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterByEmailRequest) ProtoMessage() {}

func (x *RegisterByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterByEmailRequest.ProtoReflect.Descriptor instead.
func (*RegisterByEmailRequest) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterByEmailRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterByEmailRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterByEmailRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterByEmailRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// RegisterByEmailResponse 邮箱注册响应
type RegisterByEmailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// 用户 ID（雪花 ID 格式）
	UserId string `protobuf:"bytes,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 登录 Token（可用于后续认证）
	Token         string `protobuf:"bytes,12,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterByEmailResponse) Reset() {
	*x = RegisterByEmailResponse{}
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterByEmailResponse) ProtoMessage() {}

func (x *RegisterByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterByEmailResponse.ProtoReflect.Descriptor instead.
func (*RegisterByEmailResponse) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterByEmailResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *RegisterByEmailResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterByEmailResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// PasswordLoginRequest 密码登录请求（Resource Owner Password Credentials Grant）
type PasswordLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户标识（用户名、邮箱或手机号）
	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	// 用户密码（明文）
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 授权范围（必须包含 openid）
	Scope string `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	// 客户端 IP 地址（可选，用于安全审计）
	ClientIp *string `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3,oneof" json:"client_ip,omitempty"`
	// 客户端 User-Agent（可选，用于安全审计）
	UserAgent     *string `protobuf:"bytes,5,opt,name=user_agent,json=userAgent,proto3,oneof" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordLoginRequest) Reset() {
	*x = PasswordLoginRequest{}
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordLoginRequest) ProtoMessage() {}

func (x *PasswordLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordLoginRequest.ProtoReflect.Descriptor instead.
func (*PasswordLoginRequest) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *PasswordLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PasswordLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PasswordLoginRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PasswordLoginRequest) GetClientIp() string {
	if x != nil && x.ClientIp != nil {
		return *x.ClientIp
	}
	return ""
}

func (x *PasswordLoginRequest) GetUserAgent() string {
	if x != nil && x.UserAgent != nil {
		return *x.UserAgent
	}
	return ""
}

// PasswordLoginResponse 密码登录响应
type PasswordLoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// Access Token（UUID 格式）
	AccessToken string `protobuf:"bytes,11,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// Token 类型（固定为 "Bearer"）
	TokenType string `protobuf:"bytes,12,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	// Access Token 有效期（秒）
	ExpiresIn int64 `protobuf:"varint,13,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	// Refresh Token（UUID 格式）
	RefreshToken *string `protobuf:"bytes,14,opt,name=refresh_token,json=refreshToken,proto3,oneof" json:"refresh_token,omitempty"`
	// 授权范围
	Scope *string `protobuf:"bytes,15,opt,name=scope,proto3,oneof" json:"scope,omitempty"`
	// ID Token（JWT 格式，scope 包含 openid 时返回）
	IdToken       *string `protobuf:"bytes,16,opt,name=id_token,json=idToken,proto3,oneof" json:"id_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordLoginResponse) Reset() {
	*x = PasswordLoginResponse{}
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordLoginResponse) ProtoMessage() {}

func (x *PasswordLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordLoginResponse.ProtoReflect.Descriptor instead.
func (*PasswordLoginResponse) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *PasswordLoginResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *PasswordLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *PasswordLoginResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *PasswordLoginResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *PasswordLoginResponse) GetRefreshToken() string {
	if x != nil && x.RefreshToken != nil {
		return *x.RefreshToken
	}
	return ""
}

func (x *PasswordLoginResponse) GetScope() string {
	if x != nil && x.Scope != nil {
		return *x.Scope
	}
	return ""
}

func (x *PasswordLoginResponse) GetIdToken() string {
	if x != nil && x.IdToken != nil {
		return *x.IdToken
	}
	return ""
}

// ChangePasswordRequest 修改密码请求
type ChangePasswordRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID（雪花 ID 格式）
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 旧密码（强制重置模式下可省略）
	OldPassword *string `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3,oneof" json:"old_password,omitempty"`
	// 新密码（至少 6 位且包含字母和数字）
	NewPassword   string `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ChangePasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil && x.OldPassword != nil {
		return *x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

// ChangePasswordResponse 修改密码响应
type ChangePasswordResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse  *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *ChangePasswordResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

// RevokeTokenRequest 注销 Token 请求
type RevokeTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token 类型提示（可选）
	// - access_token: 仅注销 Access Token
	// - refresh_token: 仅注销 Refresh Token
	// - 留空: 默认注销 Access Token
	TokenTypeHint *string `protobuf:"bytes,1,opt,name=token_type_hint,json=tokenTypeHint,proto3,oneof" json:"token_type_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_auth_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeTokenRequest) GetTokenTypeHint() string {
	if x != nil && x.TokenTypeHint != nil {
		return *x.TokenTypeHint
	}
	return ""
}

// RevokeTokenResponse 注销 Token 响应
type RevokeTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse  *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeTokenResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

var File_beacon_sso_v1_auth_proto protoreflect.FileDescriptor

const file_beacon_sso_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18beacon/sso/v1/auth.proto\x12\rbeacon.sso.v1\x1a\x0flink/base.proto\"\x96\x01\n" +
	"\x16RegisterByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\"\x82\x01\n" +
	"\x17RegisterByEmailResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12\x17\n" +
	"\auser_id\x18\v \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\f \x01(\tR\x05token\"\xc7\x01\n" +
	"\x14PasswordLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12 \n" +
	"\tclient_ip\x18\x04 \x01(\tH\x00R\bclientIp\x88\x01\x01\x12\"\n" +
	"\n" +
	"user_agent\x18\x05 \x01(\tH\x01R\tuserAgent\x88\x01\x01B\f\n" +
	"\n" +
	"_client_ipB\r\n" +
	"\v_user_agent\"\xc0\x02\n" +
	"\x15PasswordLoginResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12!\n" +
	"\faccess_token\x18\v \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\f \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\r \x01(\x03R\texpiresIn\x12(\n" +
	"\rrefresh_token\x18\x0e \x01(\tH\x00R\frefreshToken\x88\x01\x01\x12\x19\n" +
	"\x05scope\x18\x0f \x01(\tH\x01R\x05scope\x88\x01\x01\x12\x1e\n" +
	"\bid_token\x18\x10 \x01(\tH\x02R\aidToken\x88\x01\x01B\x10\n" +
	"\x0e_refresh_tokenB\b\n" +
	"\x06_scopeB\v\n" +
	"\t_id_token\"\x8c\x01\n" +
	"\x15ChangePasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\fold_password\x18\x02 \x01(\tH\x00R\voldPassword\x88\x01\x01\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPasswordB\x0f\n" +
	"\r_old_password\"R\n" +
	"\x16ChangePasswordResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\"U\n" +
	"\x12RevokeTokenRequest\x12+\n" +
	"\x0ftoken_type_hint\x18\x01 \x01(\tH\x00R\rtokenTypeHint\x88\x01\x01B\x12\n" +
	"\x10_token_type_hint\"O\n" +
	"\x13RevokeTokenResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse2\x80\x03\n" +
	"\vAuthService\x12`\n" +
	"\x0fRegisterByEmail\x12%.beacon.sso.v1.RegisterByEmailRequest\x1a&.beacon.sso.v1.RegisterByEmailResponse\x12Z\n" +
	"\rPasswordLogin\x12#.beacon.sso.v1.PasswordLoginRequest\x1a$.beacon.sso.v1.PasswordLoginResponse\x12]\n" +
	"\x0eChangePassword\x12$.beacon.sso.v1.ChangePasswordRequest\x1a%.beacon.sso.v1.ChangePasswordResponse\x12T\n" +
	"\vRevokeToken\x12!.beacon.sso.v1.RevokeTokenRequest\x1a\".beacon.sso.v1.RevokeTokenResponseBDZBgithub.com/phalanx-labs/beacon-sso-sdk/client/api/beacon/sso/v1;pbb\x06proto3"

var (
	file_beacon_sso_v1_auth_proto_rawDescOnce sync.Once
	file_beacon_sso_v1_auth_proto_rawDescData []byte
)

func file_beacon_sso_v1_auth_proto_rawDescGZIP() []byte {
	file_beacon_sso_v1_auth_proto_rawDescOnce.Do(func() {
		file_beacon_sso_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beacon_sso_v1_auth_proto_rawDesc), len(file_beacon_sso_v1_auth_proto_rawDesc)))
	})
	return file_beacon_sso_v1_auth_proto_rawDescData
}

var file_beacon_sso_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_beacon_sso_v1_auth_proto_goTypes = []any{
	(*RegisterByEmailRequest)(nil),  // 0: beacon.sso.v1.RegisterByEmailRequest
	(*RegisterByEmailResponse)(nil), // 1: beacon.sso.v1.RegisterByEmailResponse
	(*PasswordLoginRequest)(nil),    // 2: beacon.sso.v1.PasswordLoginRequest
	(*PasswordLoginResponse)(nil),   // 3: beacon.sso.v1.PasswordLoginResponse
	(*ChangePasswordRequest)(nil),   // 4: beacon.sso.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil),  // 5: beacon.sso.v1.ChangePasswordResponse
	(*RevokeTokenRequest)(nil),      // 6: beacon.sso.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),     // 7: beacon.sso.v1.RevokeTokenResponse
	(*generate.BaseResponse)(nil),   // 8: xBase.BaseResponse
}
var file_beacon_sso_v1_auth_proto_depIdxs = []int32{
	8, // 0: beacon.sso.v1.RegisterByEmailResponse.base_response:type_name -> xBase.BaseResponse
	8, // 1: beacon.sso.v1.PasswordLoginResponse.base_response:type_name -> xBase.BaseResponse
	8, // 2: beacon.sso.v1.ChangePasswordResponse.base_response:type_name -> xBase.BaseResponse
	8, // 3: beacon.sso.v1.RevokeTokenResponse.base_response:type_name -> xBase.BaseResponse
	0, // 4: beacon.sso.v1.AuthService.RegisterByEmail:input_type -> beacon.sso.v1.RegisterByEmailRequest
	2, // 5: beacon.sso.v1.AuthService.PasswordLogin:input_type -> beacon.sso.v1.PasswordLoginRequest
	4, // 6: beacon.sso.v1.AuthService.ChangePassword:input_type -> beacon.sso.v1.ChangePasswordRequest
	6, // 7: beacon.sso.v1.AuthService.RevokeToken:input_type -> beacon.sso.v1.RevokeTokenRequest
	1, // 8: beacon.sso.v1.AuthService.RegisterByEmail:output_type -> beacon.sso.v1.RegisterByEmailResponse
	3, // 9: beacon.sso.v1.AuthService.PasswordLogin:output_type -> beacon.sso.v1.PasswordLoginResponse
	5, // 10: beacon.sso.v1.AuthService.ChangePassword:output_type -> beacon.sso.v1.ChangePasswordResponse
	7, // 11: beacon.sso.v1.AuthService.RevokeToken:output_type -> beacon.sso.v1.RevokeTokenResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_beacon_sso_v1_auth_proto_init() }
func file_beacon_sso_v1_auth_proto_init() {
	if File_beacon_sso_v1_auth_proto != nil {
		return
	}
	file_beacon_sso_v1_auth_proto_msgTypes[2].OneofWrappers = []any{}
	file_beacon_sso_v1_auth_proto_msgTypes[3].OneofWrappers = []any{}
	file_beacon_sso_v1_auth_proto_msgTypes[4].OneofWrappers = []any{}
	file_beacon_sso_v1_auth_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beacon_sso_v1_auth_proto_rawDesc), len(file_beacon_sso_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beacon_sso_v1_auth_proto_goTypes,
		DependencyIndexes: file_beacon_sso_v1_auth_proto_depIdxs,
		MessageInfos:      file_beacon_sso_v1_auth_proto_msgTypes,
	}.Build()
	File_beacon_sso_v1_auth_proto = out.File
	file_beacon_sso_v1_auth_proto_goTypes = nil
	file_beacon_sso_v1_auth_proto_depIdxs = nil
}
