// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: beacon/sso/v1/auth.proto

package pb

import (
	generate "github.com/bamboo-services/bamboo-base-go/plugins/grpc/generate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterByEmailRequest 邮箱注册请求
type RegisterByEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 邮箱地址（必填）
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// 验证码（必填）
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 用户名（可选，不填则自动生成）
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	// 密码（必填，至少 6 位且包含字母和数字）
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	// 昵称（可选，不填则使用用户名或自动生成）
	Nickname      string `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterByEmailRequest) Reset() {
	*x = RegisterByEmailRequest{}
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterByEmailRequest) ProtoMessage() {}

func (x *RegisterByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterByEmailRequest.ProtoReflect.Descriptor instead.
func (*RegisterByEmailRequest) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterByEmailRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterByEmailRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterByEmailRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterByEmailRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// RegisterByEmailResponse 邮箱注册响应
type RegisterByEmailResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// 用户 ID（雪花 ID 格式）
	UserId string `protobuf:"bytes,11,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 登录 Token（可用于后续认证）
	Token         string `protobuf:"bytes,12,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterByEmailResponse) Reset() {
	*x = RegisterByEmailResponse{}
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterByEmailResponse) ProtoMessage() {}

func (x *RegisterByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterByEmailResponse.ProtoReflect.Descriptor instead.
func (*RegisterByEmailResponse) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterByEmailResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *RegisterByEmailResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterByEmailResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_beacon_sso_v1_auth_proto protoreflect.FileDescriptor

const file_beacon_sso_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18beacon/sso/v1/auth.proto\x12\rbeacon.sso.v1\x1a\x0flink/base.proto\"\x96\x01\n" +
	"\x16RegisterByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\"\x82\x01\n" +
	"\x17RegisterByEmailResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12\x17\n" +
	"\auser_id\x18\v \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\f \x01(\tR\x05token2o\n" +
	"\vAuthService\x12`\n" +
	"\x0fRegisterByEmail\x12%.beacon.sso.v1.RegisterByEmailRequest\x1a&.beacon.sso.v1.RegisterByEmailResponseBDZBgithub.com/phalanx-labs/beacon-sso-sdk/client/api/beacon/sso/v1;pbb\x06proto3"

var (
	file_beacon_sso_v1_auth_proto_rawDescOnce sync.Once
	file_beacon_sso_v1_auth_proto_rawDescData []byte
)

func file_beacon_sso_v1_auth_proto_rawDescGZIP() []byte {
	file_beacon_sso_v1_auth_proto_rawDescOnce.Do(func() {
		file_beacon_sso_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beacon_sso_v1_auth_proto_rawDesc), len(file_beacon_sso_v1_auth_proto_rawDesc)))
	})
	return file_beacon_sso_v1_auth_proto_rawDescData
}

var file_beacon_sso_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_beacon_sso_v1_auth_proto_goTypes = []any{
	(*RegisterByEmailRequest)(nil),  // 0: beacon.sso.v1.RegisterByEmailRequest
	(*RegisterByEmailResponse)(nil), // 1: beacon.sso.v1.RegisterByEmailResponse
	(*generate.BaseResponse)(nil),   // 2: xBase.BaseResponse
}
var file_beacon_sso_v1_auth_proto_depIdxs = []int32{
	2, // 0: beacon.sso.v1.RegisterByEmailResponse.base_response:type_name -> xBase.BaseResponse
	0, // 1: beacon.sso.v1.AuthService.RegisterByEmail:input_type -> beacon.sso.v1.RegisterByEmailRequest
	1, // 2: beacon.sso.v1.AuthService.RegisterByEmail:output_type -> beacon.sso.v1.RegisterByEmailResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_beacon_sso_v1_auth_proto_init() }
func file_beacon_sso_v1_auth_proto_init() {
	if File_beacon_sso_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beacon_sso_v1_auth_proto_rawDesc), len(file_beacon_sso_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beacon_sso_v1_auth_proto_goTypes,
		DependencyIndexes: file_beacon_sso_v1_auth_proto_depIdxs,
		MessageInfos:      file_beacon_sso_v1_auth_proto_msgTypes,
	}.Build()
	File_beacon_sso_v1_auth_proto = out.File
	file_beacon_sso_v1_auth_proto_goTypes = nil
	file_beacon_sso_v1_auth_proto_depIdxs = nil
}
