// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: beacon/sso/v1/merchant_service.proto

package pb

import (
	generate "github.com/bamboo-services/bamboo-base-go/plugins/grpc/generate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MerchantTag 商户标签信息
type MerchantTag struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 标签 ID（雪花 ID 格式）
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 标签代码（用于匹配，仅允许字母数字下划线）
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// 标签名称（展示用）
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 标签描述
	Description *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// 颜色代码（HEX 格式）
	Color *string `protobuf:"bytes,5,opt,name=color,proto3,oneof" json:"color,omitempty"`
	// 图标标识
	Icon *string `protobuf:"bytes,6,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	// 排序权重
	SortOrder int32 `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	// 状态（0 禁用 / 1 启用）
	Status        int32 `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantTag) Reset() {
	*x = MerchantTag{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantTag) ProtoMessage() {}

func (x *MerchantTag) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantTag.ProtoReflect.Descriptor instead.
func (*MerchantTag) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{0}
}

func (x *MerchantTag) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MerchantTag) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *MerchantTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MerchantTag) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *MerchantTag) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *MerchantTag) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *MerchantTag) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *MerchantTag) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// GetMerchantTagsRequest 获取商户标签列表请求
type GetMerchantTagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否仅返回启用的标签
	EnabledOnly   *bool `protobuf:"varint,1,opt,name=enabled_only,json=enabledOnly,proto3,oneof" json:"enabled_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantTagsRequest) Reset() {
	*x = GetMerchantTagsRequest{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantTagsRequest) ProtoMessage() {}

func (x *GetMerchantTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantTagsRequest.ProtoReflect.Descriptor instead.
func (*GetMerchantTagsRequest) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMerchantTagsRequest) GetEnabledOnly() bool {
	if x != nil && x.EnabledOnly != nil {
		return *x.EnabledOnly
	}
	return false
}

// GetMerchantTagsResponse 获取商户标签列表响应
type GetMerchantTagsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// 标签列表
	Tags          []*MerchantTag `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMerchantTagsResponse) Reset() {
	*x = GetMerchantTagsResponse{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMerchantTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMerchantTagsResponse) ProtoMessage() {}

func (x *GetMerchantTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMerchantTagsResponse.ProtoReflect.Descriptor instead.
func (*GetMerchantTagsResponse) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetMerchantTagsResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetMerchantTagsResponse) GetTags() []*MerchantTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// GetUserTagsRequest 获取用户标签列表请求
type GetUserTagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID（雪花 ID 格式）
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 是否仅返回启用的标签
	EnabledOnly   *bool `protobuf:"varint,2,opt,name=enabled_only,json=enabledOnly,proto3,oneof" json:"enabled_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTagsRequest) Reset() {
	*x = GetUserTagsRequest{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTagsRequest) ProtoMessage() {}

func (x *GetUserTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTagsRequest.ProtoReflect.Descriptor instead.
func (*GetUserTagsRequest) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserTagsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserTagsRequest) GetEnabledOnly() bool {
	if x != nil && x.EnabledOnly != nil {
		return *x.EnabledOnly
	}
	return false
}

// GetUserTagsResponse 获取用户标签列表响应
type GetUserTagsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// 标签列表
	Tags          []*MerchantTag `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTagsResponse) Reset() {
	*x = GetUserTagsResponse{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTagsResponse) ProtoMessage() {}

func (x *GetUserTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTagsResponse.ProtoReflect.Descriptor instead.
func (*GetUserTagsResponse) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserTagsResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetUserTagsResponse) GetTags() []*MerchantTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// CheckUserHasTagRequest 检查用户是否有指定标签请求
type CheckUserHasTagRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID（雪花 ID 格式）
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 标签代码（用于匹配）
	TagCode       string `protobuf:"bytes,2,opt,name=tag_code,json=tagCode,proto3" json:"tag_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserHasTagRequest) Reset() {
	*x = CheckUserHasTagRequest{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserHasTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserHasTagRequest) ProtoMessage() {}

func (x *CheckUserHasTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserHasTagRequest.ProtoReflect.Descriptor instead.
func (*CheckUserHasTagRequest) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{5}
}

func (x *CheckUserHasTagRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckUserHasTagRequest) GetTagCode() string {
	if x != nil {
		return x.TagCode
	}
	return ""
}

// CheckUserHasTagResponse 检查用户是否有指定标签响应
type CheckUserHasTagResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// 用户是否拥有该标签
	HasTag        bool `protobuf:"varint,11,opt,name=has_tag,json=hasTag,proto3" json:"has_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserHasTagResponse) Reset() {
	*x = CheckUserHasTagResponse{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserHasTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserHasTagResponse) ProtoMessage() {}

func (x *CheckUserHasTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserHasTagResponse.ProtoReflect.Descriptor instead.
func (*CheckUserHasTagResponse) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{6}
}

func (x *CheckUserHasTagResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *CheckUserHasTagResponse) GetHasTag() bool {
	if x != nil {
		return x.HasTag
	}
	return false
}

// MerchantAnnouncement 商户公告信息
type MerchantAnnouncement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 公告 ID（雪花 ID 格式）
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 公告标题
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// 公告内容
	Content string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// 公告范围（1 商户 / 2 应用）
	Scope int32 `protobuf:"varint,4,opt,name=scope,proto3" json:"scope,omitempty"`
	// 展示截止时间（RFC3339 格式）
	DisplayUntil *string `protobuf:"bytes,5,opt,name=display_until,json=displayUntil,proto3,oneof" json:"display_until,omitempty"`
	// 创建时间（RFC3339 格式）
	CreatedAt     string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerchantAnnouncement) Reset() {
	*x = MerchantAnnouncement{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerchantAnnouncement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerchantAnnouncement) ProtoMessage() {}

func (x *MerchantAnnouncement) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerchantAnnouncement.ProtoReflect.Descriptor instead.
func (*MerchantAnnouncement) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{7}
}

func (x *MerchantAnnouncement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MerchantAnnouncement) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MerchantAnnouncement) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MerchantAnnouncement) GetScope() int32 {
	if x != nil {
		return x.Scope
	}
	return 0
}

func (x *MerchantAnnouncement) GetDisplayUntil() string {
	if x != nil && x.DisplayUntil != nil {
		return *x.DisplayUntil
	}
	return ""
}

func (x *MerchantAnnouncement) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// AnnouncementListMeta 公告列表元信息（用于客户端判断是否需要重新展示）
type AnnouncementListMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 所有公告内容的 MD5 哈希值（用于快速判断是否有变化）
	Md5Hash string `protobuf:"bytes,1,opt,name=md5_hash,json=md5Hash,proto3" json:"md5_hash,omitempty"`
	// 所有公告内容的 SHA256 哈希值（用于精确判断）
	Sha256Hash string `protobuf:"bytes,2,opt,name=sha256_hash,json=sha256Hash,proto3" json:"sha256_hash,omitempty"`
	// 公告数量
	Count int32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// 生成时间（RFC3339 格式）
	GeneratedAt   string `protobuf:"bytes,4,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnnouncementListMeta) Reset() {
	*x = AnnouncementListMeta{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementListMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementListMeta) ProtoMessage() {}

func (x *AnnouncementListMeta) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementListMeta.ProtoReflect.Descriptor instead.
func (*AnnouncementListMeta) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{8}
}

func (x *AnnouncementListMeta) GetMd5Hash() string {
	if x != nil {
		return x.Md5Hash
	}
	return ""
}

func (x *AnnouncementListMeta) GetSha256Hash() string {
	if x != nil {
		return x.Sha256Hash
	}
	return ""
}

func (x *AnnouncementListMeta) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AnnouncementListMeta) GetGeneratedAt() string {
	if x != nil {
		return x.GeneratedAt
	}
	return ""
}

// GetRecentAnnouncementsRequest 获取最近公告请求
type GetRecentAnnouncementsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 最大返回数量（默认 10，最大 20）
	Limit *int32 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// 是否仅返回未过期的公告
	ActiveOnly    *bool `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3,oneof" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentAnnouncementsRequest) Reset() {
	*x = GetRecentAnnouncementsRequest{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentAnnouncementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentAnnouncementsRequest) ProtoMessage() {}

func (x *GetRecentAnnouncementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentAnnouncementsRequest.ProtoReflect.Descriptor instead.
func (*GetRecentAnnouncementsRequest) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetRecentAnnouncementsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetRecentAnnouncementsRequest) GetActiveOnly() bool {
	if x != nil && x.ActiveOnly != nil {
		return *x.ActiveOnly
	}
	return false
}

// GetRecentAnnouncementsResponse 获取最近公告响应
type GetRecentAnnouncementsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// 公告列表（最多 10 条）
	Announcements []*MerchantAnnouncement `protobuf:"bytes,11,rep,name=announcements,proto3" json:"announcements,omitempty"`
	// 列表元信息（包含哈希值用于客户端判断是否需要重新展示）
	Meta          *AnnouncementListMeta `protobuf:"bytes,12,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecentAnnouncementsResponse) Reset() {
	*x = GetRecentAnnouncementsResponse{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecentAnnouncementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecentAnnouncementsResponse) ProtoMessage() {}

func (x *GetRecentAnnouncementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecentAnnouncementsResponse.ProtoReflect.Descriptor instead.
func (*GetRecentAnnouncementsResponse) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetRecentAnnouncementsResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetRecentAnnouncementsResponse) GetAnnouncements() []*MerchantAnnouncement {
	if x != nil {
		return x.Announcements
	}
	return nil
}

func (x *GetRecentAnnouncementsResponse) GetMeta() *AnnouncementListMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

// GetAnnouncementRequest 获取单个公告请求
type GetAnnouncementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 公告 ID（雪花 ID 格式）
	AnnouncementId string `protobuf:"bytes,1,opt,name=announcement_id,json=announcementId,proto3" json:"announcement_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAnnouncementRequest) Reset() {
	*x = GetAnnouncementRequest{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementRequest) ProtoMessage() {}

func (x *GetAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*GetAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetAnnouncementRequest) GetAnnouncementId() string {
	if x != nil {
		return x.AnnouncementId
	}
	return ""
}

// GetAnnouncementResponse 获取单个公告响应
type GetAnnouncementResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// 公告详情
	Announcement  *MerchantAnnouncement `protobuf:"bytes,11,opt,name=announcement,proto3" json:"announcement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnnouncementResponse) Reset() {
	*x = GetAnnouncementResponse{}
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnnouncementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnnouncementResponse) ProtoMessage() {}

func (x *GetAnnouncementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_merchant_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnnouncementResponse.ProtoReflect.Descriptor instead.
func (*GetAnnouncementResponse) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_merchant_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetAnnouncementResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetAnnouncementResponse) GetAnnouncement() *MerchantAnnouncement {
	if x != nil {
		return x.Announcement
	}
	return nil
}

var File_beacon_sso_v1_merchant_service_proto protoreflect.FileDescriptor

const file_beacon_sso_v1_merchant_service_proto_rawDesc = "" +
	"\n" +
	"$beacon/sso/v1/merchant_service.proto\x12\rbeacon.sso.v1\x1a\x0flink/base.proto\"\xfa\x01\n" +
	"\vMerchantTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x05 \x01(\tH\x01R\x05color\x88\x01\x01\x12\x17\n" +
	"\x04icon\x18\x06 \x01(\tH\x02R\x04icon\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06statusB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_colorB\a\n" +
	"\x05_icon\"Q\n" +
	"\x16GetMerchantTagsRequest\x12&\n" +
	"\fenabled_only\x18\x01 \x01(\bH\x00R\venabledOnly\x88\x01\x01B\x0f\n" +
	"\r_enabled_only\"\x83\x01\n" +
	"\x17GetMerchantTagsResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12.\n" +
	"\x04tags\x18\v \x03(\v2\x1a.beacon.sso.v1.MerchantTagR\x04tags\"f\n" +
	"\x12GetUserTagsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\fenabled_only\x18\x02 \x01(\bH\x00R\venabledOnly\x88\x01\x01B\x0f\n" +
	"\r_enabled_only\"\x7f\n" +
	"\x13GetUserTagsResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12.\n" +
	"\x04tags\x18\v \x03(\v2\x1a.beacon.sso.v1.MerchantTagR\x04tags\"L\n" +
	"\x16CheckUserHasTagRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\btag_code\x18\x02 \x01(\tR\atagCode\"l\n" +
	"\x17CheckUserHasTagResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12\x17\n" +
	"\ahas_tag\x18\v \x01(\bR\x06hasTag\"\xc7\x01\n" +
	"\x14MerchantAnnouncement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\x05R\x05scope\x12(\n" +
	"\rdisplay_until\x18\x05 \x01(\tH\x00R\fdisplayUntil\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAtB\x10\n" +
	"\x0e_display_until\"\x8b\x01\n" +
	"\x14AnnouncementListMeta\x12\x19\n" +
	"\bmd5_hash\x18\x01 \x01(\tR\amd5Hash\x12\x1f\n" +
	"\vsha256_hash\x18\x02 \x01(\tR\n" +
	"sha256Hash\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12!\n" +
	"\fgenerated_at\x18\x04 \x01(\tR\vgeneratedAt\"z\n" +
	"\x1dGetRecentAnnouncementsRequest\x12\x19\n" +
	"\x05limit\x18\x01 \x01(\x05H\x00R\x05limit\x88\x01\x01\x12$\n" +
	"\vactive_only\x18\x02 \x01(\bH\x01R\n" +
	"activeOnly\x88\x01\x01B\b\n" +
	"\x06_limitB\x0e\n" +
	"\f_active_only\"\xde\x01\n" +
	"\x1eGetRecentAnnouncementsResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12I\n" +
	"\rannouncements\x18\v \x03(\v2#.beacon.sso.v1.MerchantAnnouncementR\rannouncements\x127\n" +
	"\x04meta\x18\f \x01(\v2#.beacon.sso.v1.AnnouncementListMetaR\x04meta\"A\n" +
	"\x16GetAnnouncementRequest\x12'\n" +
	"\x0fannouncement_id\x18\x01 \x01(\tR\x0eannouncementId\"\x9c\x01\n" +
	"\x17GetAnnouncementResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12G\n" +
	"\fannouncement\x18\v \x01(\v2#.beacon.sso.v1.MerchantAnnouncementR\fannouncement2\x84\x04\n" +
	"\x0fMerchantService\x12`\n" +
	"\x0fGetMerchantTags\x12%.beacon.sso.v1.GetMerchantTagsRequest\x1a&.beacon.sso.v1.GetMerchantTagsResponse\x12T\n" +
	"\vGetUserTags\x12!.beacon.sso.v1.GetUserTagsRequest\x1a\".beacon.sso.v1.GetUserTagsResponse\x12`\n" +
	"\x0fCheckUserHasTag\x12%.beacon.sso.v1.CheckUserHasTagRequest\x1a&.beacon.sso.v1.CheckUserHasTagResponse\x12u\n" +
	"\x16GetRecentAnnouncements\x12,.beacon.sso.v1.GetRecentAnnouncementsRequest\x1a-.beacon.sso.v1.GetRecentAnnouncementsResponse\x12`\n" +
	"\x0fGetAnnouncement\x12%.beacon.sso.v1.GetAnnouncementRequest\x1a&.beacon.sso.v1.GetAnnouncementResponseBDZBgithub.com/phalanx-labs/beacon-sso-sdk/client/api/beacon/sso/v1;pbb\x06proto3"

var (
	file_beacon_sso_v1_merchant_service_proto_rawDescOnce sync.Once
	file_beacon_sso_v1_merchant_service_proto_rawDescData []byte
)

func file_beacon_sso_v1_merchant_service_proto_rawDescGZIP() []byte {
	file_beacon_sso_v1_merchant_service_proto_rawDescOnce.Do(func() {
		file_beacon_sso_v1_merchant_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beacon_sso_v1_merchant_service_proto_rawDesc), len(file_beacon_sso_v1_merchant_service_proto_rawDesc)))
	})
	return file_beacon_sso_v1_merchant_service_proto_rawDescData
}

var file_beacon_sso_v1_merchant_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_beacon_sso_v1_merchant_service_proto_goTypes = []any{
	(*MerchantTag)(nil),                    // 0: beacon.sso.v1.MerchantTag
	(*GetMerchantTagsRequest)(nil),         // 1: beacon.sso.v1.GetMerchantTagsRequest
	(*GetMerchantTagsResponse)(nil),        // 2: beacon.sso.v1.GetMerchantTagsResponse
	(*GetUserTagsRequest)(nil),             // 3: beacon.sso.v1.GetUserTagsRequest
	(*GetUserTagsResponse)(nil),            // 4: beacon.sso.v1.GetUserTagsResponse
	(*CheckUserHasTagRequest)(nil),         // 5: beacon.sso.v1.CheckUserHasTagRequest
	(*CheckUserHasTagResponse)(nil),        // 6: beacon.sso.v1.CheckUserHasTagResponse
	(*MerchantAnnouncement)(nil),           // 7: beacon.sso.v1.MerchantAnnouncement
	(*AnnouncementListMeta)(nil),           // 8: beacon.sso.v1.AnnouncementListMeta
	(*GetRecentAnnouncementsRequest)(nil),  // 9: beacon.sso.v1.GetRecentAnnouncementsRequest
	(*GetRecentAnnouncementsResponse)(nil), // 10: beacon.sso.v1.GetRecentAnnouncementsResponse
	(*GetAnnouncementRequest)(nil),         // 11: beacon.sso.v1.GetAnnouncementRequest
	(*GetAnnouncementResponse)(nil),        // 12: beacon.sso.v1.GetAnnouncementResponse
	(*generate.BaseResponse)(nil),          // 13: xBase.BaseResponse
}
var file_beacon_sso_v1_merchant_service_proto_depIdxs = []int32{
	13, // 0: beacon.sso.v1.GetMerchantTagsResponse.base_response:type_name -> xBase.BaseResponse
	0,  // 1: beacon.sso.v1.GetMerchantTagsResponse.tags:type_name -> beacon.sso.v1.MerchantTag
	13, // 2: beacon.sso.v1.GetUserTagsResponse.base_response:type_name -> xBase.BaseResponse
	0,  // 3: beacon.sso.v1.GetUserTagsResponse.tags:type_name -> beacon.sso.v1.MerchantTag
	13, // 4: beacon.sso.v1.CheckUserHasTagResponse.base_response:type_name -> xBase.BaseResponse
	13, // 5: beacon.sso.v1.GetRecentAnnouncementsResponse.base_response:type_name -> xBase.BaseResponse
	7,  // 6: beacon.sso.v1.GetRecentAnnouncementsResponse.announcements:type_name -> beacon.sso.v1.MerchantAnnouncement
	8,  // 7: beacon.sso.v1.GetRecentAnnouncementsResponse.meta:type_name -> beacon.sso.v1.AnnouncementListMeta
	13, // 8: beacon.sso.v1.GetAnnouncementResponse.base_response:type_name -> xBase.BaseResponse
	7,  // 9: beacon.sso.v1.GetAnnouncementResponse.announcement:type_name -> beacon.sso.v1.MerchantAnnouncement
	1,  // 10: beacon.sso.v1.MerchantService.GetMerchantTags:input_type -> beacon.sso.v1.GetMerchantTagsRequest
	3,  // 11: beacon.sso.v1.MerchantService.GetUserTags:input_type -> beacon.sso.v1.GetUserTagsRequest
	5,  // 12: beacon.sso.v1.MerchantService.CheckUserHasTag:input_type -> beacon.sso.v1.CheckUserHasTagRequest
	9,  // 13: beacon.sso.v1.MerchantService.GetRecentAnnouncements:input_type -> beacon.sso.v1.GetRecentAnnouncementsRequest
	11, // 14: beacon.sso.v1.MerchantService.GetAnnouncement:input_type -> beacon.sso.v1.GetAnnouncementRequest
	2,  // 15: beacon.sso.v1.MerchantService.GetMerchantTags:output_type -> beacon.sso.v1.GetMerchantTagsResponse
	4,  // 16: beacon.sso.v1.MerchantService.GetUserTags:output_type -> beacon.sso.v1.GetUserTagsResponse
	6,  // 17: beacon.sso.v1.MerchantService.CheckUserHasTag:output_type -> beacon.sso.v1.CheckUserHasTagResponse
	10, // 18: beacon.sso.v1.MerchantService.GetRecentAnnouncements:output_type -> beacon.sso.v1.GetRecentAnnouncementsResponse
	12, // 19: beacon.sso.v1.MerchantService.GetAnnouncement:output_type -> beacon.sso.v1.GetAnnouncementResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_beacon_sso_v1_merchant_service_proto_init() }
func file_beacon_sso_v1_merchant_service_proto_init() {
	if File_beacon_sso_v1_merchant_service_proto != nil {
		return
	}
	file_beacon_sso_v1_merchant_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_beacon_sso_v1_merchant_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_beacon_sso_v1_merchant_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_beacon_sso_v1_merchant_service_proto_msgTypes[7].OneofWrappers = []any{}
	file_beacon_sso_v1_merchant_service_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beacon_sso_v1_merchant_service_proto_rawDesc), len(file_beacon_sso_v1_merchant_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beacon_sso_v1_merchant_service_proto_goTypes,
		DependencyIndexes: file_beacon_sso_v1_merchant_service_proto_depIdxs,
		MessageInfos:      file_beacon_sso_v1_merchant_service_proto_msgTypes,
	}.Build()
	File_beacon_sso_v1_merchant_service_proto = out.File
	file_beacon_sso_v1_merchant_service_proto_goTypes = nil
	file_beacon_sso_v1_merchant_service_proto_depIdxs = nil
}
