// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: beacon/sso/v1/public.proto

package pb

import (
	generate "github.com/bamboo-services/bamboo-base-go/plugins/grpc/generate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendRegisterEmailCodeRequest 发送注册验证码请求
type SendRegisterEmailCodeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 目标邮箱地址
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRegisterEmailCodeRequest) Reset() {
	*x = SendRegisterEmailCodeRequest{}
	mi := &file_beacon_sso_v1_public_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRegisterEmailCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRegisterEmailCodeRequest) ProtoMessage() {}

func (x *SendRegisterEmailCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_public_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRegisterEmailCodeRequest.ProtoReflect.Descriptor instead.
func (*SendRegisterEmailCodeRequest) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_public_proto_rawDescGZIP(), []int{0}
}

func (x *SendRegisterEmailCodeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// SendRegisterEmailCodeResponse 发送注册验证码响应
type SendRegisterEmailCodeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse  *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendRegisterEmailCodeResponse) Reset() {
	*x = SendRegisterEmailCodeResponse{}
	mi := &file_beacon_sso_v1_public_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendRegisterEmailCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendRegisterEmailCodeResponse) ProtoMessage() {}

func (x *SendRegisterEmailCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_public_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendRegisterEmailCodeResponse.ProtoReflect.Descriptor instead.
func (*SendRegisterEmailCodeResponse) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_public_proto_rawDescGZIP(), []int{1}
}

func (x *SendRegisterEmailCodeResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

var File_beacon_sso_v1_public_proto protoreflect.FileDescriptor

const file_beacon_sso_v1_public_proto_rawDesc = "" +
	"\n" +
	"\x1abeacon/sso/v1/public.proto\x12\rbeacon.sso.v1\x1a\x0flink/base.proto\"4\n" +
	"\x1cSendRegisterEmailCodeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"Y\n" +
	"\x1dSendRegisterEmailCodeResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse2\x83\x01\n" +
	"\rPublicService\x12r\n" +
	"\x15SendRegisterEmailCode\x12+.beacon.sso.v1.SendRegisterEmailCodeRequest\x1a,.beacon.sso.v1.SendRegisterEmailCodeResponseBDZBgithub.com/phalanx-labs/beacon-sso-sdk/client/api/beacon/sso/v1;pbb\x06proto3"

var (
	file_beacon_sso_v1_public_proto_rawDescOnce sync.Once
	file_beacon_sso_v1_public_proto_rawDescData []byte
)

func file_beacon_sso_v1_public_proto_rawDescGZIP() []byte {
	file_beacon_sso_v1_public_proto_rawDescOnce.Do(func() {
		file_beacon_sso_v1_public_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beacon_sso_v1_public_proto_rawDesc), len(file_beacon_sso_v1_public_proto_rawDesc)))
	})
	return file_beacon_sso_v1_public_proto_rawDescData
}

var file_beacon_sso_v1_public_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_beacon_sso_v1_public_proto_goTypes = []any{
	(*SendRegisterEmailCodeRequest)(nil),  // 0: beacon.sso.v1.SendRegisterEmailCodeRequest
	(*SendRegisterEmailCodeResponse)(nil), // 1: beacon.sso.v1.SendRegisterEmailCodeResponse
	(*generate.BaseResponse)(nil),         // 2: xBase.BaseResponse
}
var file_beacon_sso_v1_public_proto_depIdxs = []int32{
	2, // 0: beacon.sso.v1.SendRegisterEmailCodeResponse.base_response:type_name -> xBase.BaseResponse
	0, // 1: beacon.sso.v1.PublicService.SendRegisterEmailCode:input_type -> beacon.sso.v1.SendRegisterEmailCodeRequest
	1, // 2: beacon.sso.v1.PublicService.SendRegisterEmailCode:output_type -> beacon.sso.v1.SendRegisterEmailCodeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_beacon_sso_v1_public_proto_init() }
func file_beacon_sso_v1_public_proto_init() {
	if File_beacon_sso_v1_public_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beacon_sso_v1_public_proto_rawDesc), len(file_beacon_sso_v1_public_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beacon_sso_v1_public_proto_goTypes,
		DependencyIndexes: file_beacon_sso_v1_public_proto_depIdxs,
		MessageInfos:      file_beacon_sso_v1_public_proto_msgTypes,
	}.Build()
	File_beacon_sso_v1_public_proto = out.File
	file_beacon_sso_v1_public_proto_goTypes = nil
	file_beacon_sso_v1_public_proto_depIdxs = nil
}
