// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: beacon/sso/v1/user.proto

package pb

import (
	generate "github.com/bamboo-services/bamboo-base-go/plugins/grpc/generate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Role 角色信息
type Role struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 角色代码（如 SUPER_ADMIN、ADMIN、MERCHANT）
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// 角色名称
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// 角色描述
	Description   *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_beacon_sso_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *Role) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

// User 用户信息
type User struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户 ID（雪花 ID 格式）
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 用户名
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	// 昵称
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 邮箱地址
	Email *string `protobuf:"bytes,4,opt,name=email,proto3,oneof" json:"email,omitempty"`
	// 手机号码
	Phone *string `protobuf:"bytes,5,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	// 头像 URL
	Avatar *string `protobuf:"bytes,6,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	// 性别（0 未知 / 1 男 / 2 女）
	Gender int32 `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	// 生日（ISO 8601 日期格式）
	Birthday *string `protobuf:"bytes,8,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	// 状态（0 禁用 / 1 启用）
	Status int32 `protobuf:"varint,9,opt,name=status,proto3" json:"status,omitempty"`
	// 邮箱是否已验证
	IsEmailVerified bool `protobuf:"varint,10,opt,name=is_email_verified,json=isEmailVerified,proto3" json:"is_email_verified,omitempty"`
	// 手机是否已验证
	IsPhoneVerified bool `protobuf:"varint,11,opt,name=is_phone_verified,json=isPhoneVerified,proto3" json:"is_phone_verified,omitempty"`
	// 是否需要强制重置密码
	NeedResetPassword bool `protobuf:"varint,12,opt,name=need_reset_password,json=needResetPassword,proto3" json:"need_reset_password,omitempty"`
	// 最后登录时间（ISO 8601 格式）
	LastLoginAt *string `protobuf:"bytes,13,opt,name=last_login_at,json=lastLoginAt,proto3,oneof" json:"last_login_at,omitempty"`
	// 最后登录 IP
	LastLoginIp *string `protobuf:"bytes,14,opt,name=last_login_ip,json=lastLoginIp,proto3,oneof" json:"last_login_ip,omitempty"`
	// 用户角色列表
	Roles         []*Role `protobuf:"bytes,20,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_beacon_sso_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *User) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *User) GetBirthday() string {
	if x != nil && x.Birthday != nil {
		return *x.Birthday
	}
	return ""
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetIsEmailVerified() bool {
	if x != nil {
		return x.IsEmailVerified
	}
	return false
}

func (x *User) GetIsPhoneVerified() bool {
	if x != nil {
		return x.IsPhoneVerified
	}
	return false
}

func (x *User) GetNeedResetPassword() bool {
	if x != nil {
		return x.NeedResetPassword
	}
	return false
}

func (x *User) GetLastLoginAt() string {
	if x != nil && x.LastLoginAt != nil {
		return *x.LastLoginAt
	}
	return ""
}

func (x *User) GetLastLoginIp() string {
	if x != nil && x.LastLoginIp != nil {
		return *x.LastLoginIp
	}
	return ""
}

func (x *User) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

// GetCurrentUserRequest 获取当前用户请求
type GetCurrentUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserRequest) Reset() {
	*x = GetCurrentUserRequest{}
	mi := &file_beacon_sso_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserRequest) ProtoMessage() {}

func (x *GetCurrentUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentUserRequest) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_user_proto_rawDescGZIP(), []int{2}
}

// GetCurrentUserResponse 获取当前用户响应
type GetCurrentUserResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 基础响应信息
	BaseResponse *generate.BaseResponse `protobuf:"bytes,1,opt,name=base_response,json=baseResponse,proto3" json:"base_response,omitempty"`
	// 用户信息
	User          *User `protobuf:"bytes,11,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentUserResponse) Reset() {
	*x = GetCurrentUserResponse{}
	mi := &file_beacon_sso_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentUserResponse) ProtoMessage() {}

func (x *GetCurrentUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beacon_sso_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentUserResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentUserResponse) Descriptor() ([]byte, []int) {
	return file_beacon_sso_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentUserResponse) GetBaseResponse() *generate.BaseResponse {
	if x != nil {
		return x.BaseResponse
	}
	return nil
}

func (x *GetCurrentUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_beacon_sso_v1_user_proto protoreflect.FileDescriptor

const file_beacon_sso_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x18beacon/sso/v1/user.proto\x12\rbeacon.sso.v1\x1a\x0flink/base.proto\"e\n" +
	"\x04Role\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\xc7\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x19\n" +
	"\x05email\x18\x04 \x01(\tH\x00R\x05email\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x05 \x01(\tH\x01R\x05phone\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x06 \x01(\tH\x02R\x06avatar\x88\x01\x01\x12\x16\n" +
	"\x06gender\x18\a \x01(\x05R\x06gender\x12\x1f\n" +
	"\bbirthday\x18\b \x01(\tH\x03R\bbirthday\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\t \x01(\x05R\x06status\x12*\n" +
	"\x11is_email_verified\x18\n" +
	" \x01(\bR\x0fisEmailVerified\x12*\n" +
	"\x11is_phone_verified\x18\v \x01(\bR\x0fisPhoneVerified\x12.\n" +
	"\x13need_reset_password\x18\f \x01(\bR\x11needResetPassword\x12'\n" +
	"\rlast_login_at\x18\r \x01(\tH\x04R\vlastLoginAt\x88\x01\x01\x12'\n" +
	"\rlast_login_ip\x18\x0e \x01(\tH\x05R\vlastLoginIp\x88\x01\x01\x12)\n" +
	"\x05roles\x18\x14 \x03(\v2\x13.beacon.sso.v1.RoleR\x05rolesB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\t\n" +
	"\a_avatarB\v\n" +
	"\t_birthdayB\x10\n" +
	"\x0e_last_login_atB\x10\n" +
	"\x0e_last_login_ip\"\x17\n" +
	"\x15GetCurrentUserRequest\"{\n" +
	"\x16GetCurrentUserResponse\x128\n" +
	"\rbase_response\x18\x01 \x01(\v2\x13.xBase.BaseResponseR\fbaseResponse\x12'\n" +
	"\x04user\x18\v \x01(\v2\x13.beacon.sso.v1.UserR\x04user2l\n" +
	"\vUserService\x12]\n" +
	"\x0eGetCurrentUser\x12$.beacon.sso.v1.GetCurrentUserRequest\x1a%.beacon.sso.v1.GetCurrentUserResponseBDZBgithub.com/phalanx-labs/beacon-sso-sdk/client/api/beacon/sso/v1;pbb\x06proto3"

var (
	file_beacon_sso_v1_user_proto_rawDescOnce sync.Once
	file_beacon_sso_v1_user_proto_rawDescData []byte
)

func file_beacon_sso_v1_user_proto_rawDescGZIP() []byte {
	file_beacon_sso_v1_user_proto_rawDescOnce.Do(func() {
		file_beacon_sso_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beacon_sso_v1_user_proto_rawDesc), len(file_beacon_sso_v1_user_proto_rawDesc)))
	})
	return file_beacon_sso_v1_user_proto_rawDescData
}

var file_beacon_sso_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_beacon_sso_v1_user_proto_goTypes = []any{
	(*Role)(nil),                   // 0: beacon.sso.v1.Role
	(*User)(nil),                   // 1: beacon.sso.v1.User
	(*GetCurrentUserRequest)(nil),  // 2: beacon.sso.v1.GetCurrentUserRequest
	(*GetCurrentUserResponse)(nil), // 3: beacon.sso.v1.GetCurrentUserResponse
	(*generate.BaseResponse)(nil),  // 4: xBase.BaseResponse
}
var file_beacon_sso_v1_user_proto_depIdxs = []int32{
	0, // 0: beacon.sso.v1.User.roles:type_name -> beacon.sso.v1.Role
	4, // 1: beacon.sso.v1.GetCurrentUserResponse.base_response:type_name -> xBase.BaseResponse
	1, // 2: beacon.sso.v1.GetCurrentUserResponse.user:type_name -> beacon.sso.v1.User
	2, // 3: beacon.sso.v1.UserService.GetCurrentUser:input_type -> beacon.sso.v1.GetCurrentUserRequest
	3, // 4: beacon.sso.v1.UserService.GetCurrentUser:output_type -> beacon.sso.v1.GetCurrentUserResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_beacon_sso_v1_user_proto_init() }
func file_beacon_sso_v1_user_proto_init() {
	if File_beacon_sso_v1_user_proto != nil {
		return
	}
	file_beacon_sso_v1_user_proto_msgTypes[0].OneofWrappers = []any{}
	file_beacon_sso_v1_user_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beacon_sso_v1_user_proto_rawDesc), len(file_beacon_sso_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beacon_sso_v1_user_proto_goTypes,
		DependencyIndexes: file_beacon_sso_v1_user_proto_depIdxs,
		MessageInfos:      file_beacon_sso_v1_user_proto_msgTypes,
	}.Build()
	File_beacon_sso_v1_user_proto = out.File
	file_beacon_sso_v1_user_proto_goTypes = nil
	file_beacon_sso_v1_user_proto_depIdxs = nil
}
