// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: beacon/sso/v1/auth.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/phalanx-labs/beacon-sso-sdk/client/api/beacon/sso/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "beacon.sso.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceRegisterByEmailProcedure is the fully-qualified name of the AuthService's
	// RegisterByEmail RPC.
	AuthServiceRegisterByEmailProcedure = "/beacon.sso.v1.AuthService/RegisterByEmail"
)

// AuthServiceClient is a client for the beacon.sso.v1.AuthService service.
type AuthServiceClient interface {
	// RegisterByEmail 通过邮箱注册
	//
	// 该接口用于通过邮箱验证码完成用户注册，注册成功后自动生成登录 Token。
	// 注册流程：
	// 1. 验证邮箱验证码
	// 2. 检查邮箱是否已注册
	// 3. 验证密码强度
	// 4. 创建用户账号
	// 5. 绑定邮箱并标记为已验证
	// 6. 生成登录 Token
	RegisterByEmail(context.Context, *connect.Request[v1.RegisterByEmailRequest]) (*connect.Response[v1.RegisterByEmailResponse], error)
}

// NewAuthServiceClient constructs a client for the beacon.sso.v1.AuthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_beacon_sso_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		registerByEmail: connect.NewClient[v1.RegisterByEmailRequest, v1.RegisterByEmailResponse](
			httpClient,
			baseURL+AuthServiceRegisterByEmailProcedure,
			connect.WithSchema(authServiceMethods.ByName("RegisterByEmail")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	registerByEmail *connect.Client[v1.RegisterByEmailRequest, v1.RegisterByEmailResponse]
}

// RegisterByEmail calls beacon.sso.v1.AuthService.RegisterByEmail.
func (c *authServiceClient) RegisterByEmail(ctx context.Context, req *connect.Request[v1.RegisterByEmailRequest]) (*connect.Response[v1.RegisterByEmailResponse], error) {
	return c.registerByEmail.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the beacon.sso.v1.AuthService service.
type AuthServiceHandler interface {
	// RegisterByEmail 通过邮箱注册
	//
	// 该接口用于通过邮箱验证码完成用户注册，注册成功后自动生成登录 Token。
	// 注册流程：
	// 1. 验证邮箱验证码
	// 2. 检查邮箱是否已注册
	// 3. 验证密码强度
	// 4. 创建用户账号
	// 5. 绑定邮箱并标记为已验证
	// 6. 生成登录 Token
	RegisterByEmail(context.Context, *connect.Request[v1.RegisterByEmailRequest]) (*connect.Response[v1.RegisterByEmailResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_beacon_sso_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceRegisterByEmailHandler := connect.NewUnaryHandler(
		AuthServiceRegisterByEmailProcedure,
		svc.RegisterByEmail,
		connect.WithSchema(authServiceMethods.ByName("RegisterByEmail")),
		connect.WithHandlerOptions(opts...),
	)
	return "/beacon.sso.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceRegisterByEmailProcedure:
			authServiceRegisterByEmailHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) RegisterByEmail(context.Context, *connect.Request[v1.RegisterByEmailRequest]) (*connect.Response[v1.RegisterByEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("beacon.sso.v1.AuthService.RegisterByEmail is not implemented"))
}
