// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: beacon/sso/v1/auth.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/phalanx-labs/beacon-sso-sdk/client/api/beacon/sso/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "beacon.sso.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceRegisterByEmailProcedure is the fully-qualified name of the AuthService's
	// RegisterByEmail RPC.
	AuthServiceRegisterByEmailProcedure = "/beacon.sso.v1.AuthService/RegisterByEmail"
	// AuthServicePasswordLoginProcedure is the fully-qualified name of the AuthService's PasswordLogin
	// RPC.
	AuthServicePasswordLoginProcedure = "/beacon.sso.v1.AuthService/PasswordLogin"
	// AuthServiceChangePasswordProcedure is the fully-qualified name of the AuthService's
	// ChangePassword RPC.
	AuthServiceChangePasswordProcedure = "/beacon.sso.v1.AuthService/ChangePassword"
	// AuthServiceRevokeTokenProcedure is the fully-qualified name of the AuthService's RevokeToken RPC.
	AuthServiceRevokeTokenProcedure = "/beacon.sso.v1.AuthService/RevokeToken"
)

// AuthServiceClient is a client for the beacon.sso.v1.AuthService service.
type AuthServiceClient interface {
	// RegisterByEmail 通过邮箱注册
	//
	// 该接口用于通过邮箱验证码完成用户注册，注册成功后自动生成登录 Token。
	// 注册流程：
	// 1. 验证邮箱验证码
	// 2. 检查邮箱是否已注册
	// 3. 验证密码强度
	// 4. 创建用户账号
	// 5. 绑定邮箱并标记为已验证
	// 6. 生成登录 Token
	RegisterByEmail(context.Context, *connect.Request[v1.RegisterByEmailRequest]) (*connect.Response[v1.RegisterByEmailResponse], error)
	// PasswordLogin 密码登录（Resource Owner Password Credentials Grant）
	//
	// 该方法实现了 OAuth 2.0 Password Grant，允许受信任的第一方客户端
	// 直接使用用户名和密码换取 Token。
	//
	// 安全特性：
	// - 仅限第一方应用使用（App.FirstParty = enabled）
	// - 支持用户名/邮箱/手机号三种登录方式（自动识别）
	// - 复用现有的密码验证逻辑（BCrypt）
	// - 复用现有的账户锁定机制
	PasswordLogin(context.Context, *connect.Request[v1.PasswordLoginRequest]) (*connect.Response[v1.PasswordLoginResponse], error)
	// ChangePassword 修改用户密码
	//
	// 该方法允许已认证的应用为用户修改密码。
	// 普通模式需要验证旧密码，强制重置模式可跳过旧密码验证。
	//
	// 模式说明：
	// - 普通模式（NeedResetPassword=false）：必须提供 old_password 进行验证
	// - 强制重置模式（NeedResetPassword=true）：可省略 old_password，直接设置新密码
	//
	// 安全特性：
	// - 旧密码验证使用 BCrypt
	// - 新密码必须满足强度要求（至少6位，包含字母和数字）
	// - 新密码不能与旧密码相同
	ChangePassword(context.Context, *connect.Request[v1.ChangePasswordRequest]) (*connect.Response[v1.ChangePasswordResponse], error)
	// RevokeToken 注销用户 Token（登出）
	//
	// 该方法用于注销当前用户的 Access Token，实现用户登出功能。
	// 符合 RFC 7009 OAuth 2.0 Token Revocation 规范。
	//
	// 使用场景：
	// - 用户主动登出
	// - Token 泄露后的紧急注销
	//
	// 安全特性：
	// - 需要有效的用户 Token 才能调用
	// - 根据 RFC 7009 规范，即使 Token 不存在也返回成功（防止信息泄露）
	RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error)
}

// NewAuthServiceClient constructs a client for the beacon.sso.v1.AuthService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_beacon_sso_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		registerByEmail: connect.NewClient[v1.RegisterByEmailRequest, v1.RegisterByEmailResponse](
			httpClient,
			baseURL+AuthServiceRegisterByEmailProcedure,
			connect.WithSchema(authServiceMethods.ByName("RegisterByEmail")),
			connect.WithClientOptions(opts...),
		),
		passwordLogin: connect.NewClient[v1.PasswordLoginRequest, v1.PasswordLoginResponse](
			httpClient,
			baseURL+AuthServicePasswordLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("PasswordLogin")),
			connect.WithClientOptions(opts...),
		),
		changePassword: connect.NewClient[v1.ChangePasswordRequest, v1.ChangePasswordResponse](
			httpClient,
			baseURL+AuthServiceChangePasswordProcedure,
			connect.WithSchema(authServiceMethods.ByName("ChangePassword")),
			connect.WithClientOptions(opts...),
		),
		revokeToken: connect.NewClient[v1.RevokeTokenRequest, v1.RevokeTokenResponse](
			httpClient,
			baseURL+AuthServiceRevokeTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("RevokeToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	registerByEmail *connect.Client[v1.RegisterByEmailRequest, v1.RegisterByEmailResponse]
	passwordLogin   *connect.Client[v1.PasswordLoginRequest, v1.PasswordLoginResponse]
	changePassword  *connect.Client[v1.ChangePasswordRequest, v1.ChangePasswordResponse]
	revokeToken     *connect.Client[v1.RevokeTokenRequest, v1.RevokeTokenResponse]
}

// RegisterByEmail calls beacon.sso.v1.AuthService.RegisterByEmail.
func (c *authServiceClient) RegisterByEmail(ctx context.Context, req *connect.Request[v1.RegisterByEmailRequest]) (*connect.Response[v1.RegisterByEmailResponse], error) {
	return c.registerByEmail.CallUnary(ctx, req)
}

// PasswordLogin calls beacon.sso.v1.AuthService.PasswordLogin.
func (c *authServiceClient) PasswordLogin(ctx context.Context, req *connect.Request[v1.PasswordLoginRequest]) (*connect.Response[v1.PasswordLoginResponse], error) {
	return c.passwordLogin.CallUnary(ctx, req)
}

// ChangePassword calls beacon.sso.v1.AuthService.ChangePassword.
func (c *authServiceClient) ChangePassword(ctx context.Context, req *connect.Request[v1.ChangePasswordRequest]) (*connect.Response[v1.ChangePasswordResponse], error) {
	return c.changePassword.CallUnary(ctx, req)
}

// RevokeToken calls beacon.sso.v1.AuthService.RevokeToken.
func (c *authServiceClient) RevokeToken(ctx context.Context, req *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error) {
	return c.revokeToken.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the beacon.sso.v1.AuthService service.
type AuthServiceHandler interface {
	// RegisterByEmail 通过邮箱注册
	//
	// 该接口用于通过邮箱验证码完成用户注册，注册成功后自动生成登录 Token。
	// 注册流程：
	// 1. 验证邮箱验证码
	// 2. 检查邮箱是否已注册
	// 3. 验证密码强度
	// 4. 创建用户账号
	// 5. 绑定邮箱并标记为已验证
	// 6. 生成登录 Token
	RegisterByEmail(context.Context, *connect.Request[v1.RegisterByEmailRequest]) (*connect.Response[v1.RegisterByEmailResponse], error)
	// PasswordLogin 密码登录（Resource Owner Password Credentials Grant）
	//
	// 该方法实现了 OAuth 2.0 Password Grant，允许受信任的第一方客户端
	// 直接使用用户名和密码换取 Token。
	//
	// 安全特性：
	// - 仅限第一方应用使用（App.FirstParty = enabled）
	// - 支持用户名/邮箱/手机号三种登录方式（自动识别）
	// - 复用现有的密码验证逻辑（BCrypt）
	// - 复用现有的账户锁定机制
	PasswordLogin(context.Context, *connect.Request[v1.PasswordLoginRequest]) (*connect.Response[v1.PasswordLoginResponse], error)
	// ChangePassword 修改用户密码
	//
	// 该方法允许已认证的应用为用户修改密码。
	// 普通模式需要验证旧密码，强制重置模式可跳过旧密码验证。
	//
	// 模式说明：
	// - 普通模式（NeedResetPassword=false）：必须提供 old_password 进行验证
	// - 强制重置模式（NeedResetPassword=true）：可省略 old_password，直接设置新密码
	//
	// 安全特性：
	// - 旧密码验证使用 BCrypt
	// - 新密码必须满足强度要求（至少6位，包含字母和数字）
	// - 新密码不能与旧密码相同
	ChangePassword(context.Context, *connect.Request[v1.ChangePasswordRequest]) (*connect.Response[v1.ChangePasswordResponse], error)
	// RevokeToken 注销用户 Token（登出）
	//
	// 该方法用于注销当前用户的 Access Token，实现用户登出功能。
	// 符合 RFC 7009 OAuth 2.0 Token Revocation 规范。
	//
	// 使用场景：
	// - 用户主动登出
	// - Token 泄露后的紧急注销
	//
	// 安全特性：
	// - 需要有效的用户 Token 才能调用
	// - 根据 RFC 7009 规范，即使 Token 不存在也返回成功（防止信息泄露）
	RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_beacon_sso_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceRegisterByEmailHandler := connect.NewUnaryHandler(
		AuthServiceRegisterByEmailProcedure,
		svc.RegisterByEmail,
		connect.WithSchema(authServiceMethods.ByName("RegisterByEmail")),
		connect.WithHandlerOptions(opts...),
	)
	authServicePasswordLoginHandler := connect.NewUnaryHandler(
		AuthServicePasswordLoginProcedure,
		svc.PasswordLogin,
		connect.WithSchema(authServiceMethods.ByName("PasswordLogin")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceChangePasswordHandler := connect.NewUnaryHandler(
		AuthServiceChangePasswordProcedure,
		svc.ChangePassword,
		connect.WithSchema(authServiceMethods.ByName("ChangePassword")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRevokeTokenHandler := connect.NewUnaryHandler(
		AuthServiceRevokeTokenProcedure,
		svc.RevokeToken,
		connect.WithSchema(authServiceMethods.ByName("RevokeToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/beacon.sso.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceRegisterByEmailProcedure:
			authServiceRegisterByEmailHandler.ServeHTTP(w, r)
		case AuthServicePasswordLoginProcedure:
			authServicePasswordLoginHandler.ServeHTTP(w, r)
		case AuthServiceChangePasswordProcedure:
			authServiceChangePasswordHandler.ServeHTTP(w, r)
		case AuthServiceRevokeTokenProcedure:
			authServiceRevokeTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) RegisterByEmail(context.Context, *connect.Request[v1.RegisterByEmailRequest]) (*connect.Response[v1.RegisterByEmailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("beacon.sso.v1.AuthService.RegisterByEmail is not implemented"))
}

func (UnimplementedAuthServiceHandler) PasswordLogin(context.Context, *connect.Request[v1.PasswordLoginRequest]) (*connect.Response[v1.PasswordLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("beacon.sso.v1.AuthService.PasswordLogin is not implemented"))
}

func (UnimplementedAuthServiceHandler) ChangePassword(context.Context, *connect.Request[v1.ChangePasswordRequest]) (*connect.Response[v1.ChangePasswordResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("beacon.sso.v1.AuthService.ChangePassword is not implemented"))
}

func (UnimplementedAuthServiceHandler) RevokeToken(context.Context, *connect.Request[v1.RevokeTokenRequest]) (*connect.Response[v1.RevokeTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("beacon.sso.v1.AuthService.RevokeToken is not implemented"))
}
