// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: beacon/sso/v1/merchant_service.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/phalanx-labs/beacon-sso-sdk/client/api/beacon/sso/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MerchantServiceName is the fully-qualified name of the MerchantService service.
	MerchantServiceName = "beacon.sso.v1.MerchantService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MerchantServiceGetMerchantTagsProcedure is the fully-qualified name of the MerchantService's
	// GetMerchantTags RPC.
	MerchantServiceGetMerchantTagsProcedure = "/beacon.sso.v1.MerchantService/GetMerchantTags"
	// MerchantServiceGetUserTagsProcedure is the fully-qualified name of the MerchantService's
	// GetUserTags RPC.
	MerchantServiceGetUserTagsProcedure = "/beacon.sso.v1.MerchantService/GetUserTags"
	// MerchantServiceCheckUserHasTagProcedure is the fully-qualified name of the MerchantService's
	// CheckUserHasTag RPC.
	MerchantServiceCheckUserHasTagProcedure = "/beacon.sso.v1.MerchantService/CheckUserHasTag"
	// MerchantServiceGetRecentAnnouncementsProcedure is the fully-qualified name of the
	// MerchantService's GetRecentAnnouncements RPC.
	MerchantServiceGetRecentAnnouncementsProcedure = "/beacon.sso.v1.MerchantService/GetRecentAnnouncements"
	// MerchantServiceGetAnnouncementProcedure is the fully-qualified name of the MerchantService's
	// GetAnnouncement RPC.
	MerchantServiceGetAnnouncementProcedure = "/beacon.sso.v1.MerchantService/GetAnnouncement"
)

// MerchantServiceClient is a client for the beacon.sso.v1.MerchantService service.
type MerchantServiceClient interface {
	// GetMerchantTags 获取当前应用所属商户的所有标签
	//
	// 返回应用所属商户下的所有标签列表，可用于客户端展示或标签匹配。
	GetMerchantTags(context.Context, *connect.Request[v1.GetMerchantTagsRequest]) (*connect.Response[v1.GetMerchantTagsResponse], error)
	// GetUserTags 获取指定用户在当前商户的所有标签
	//
	// 根据用户 ID 获取该用户在当前应用所属商户下的所有标签。
	GetUserTags(context.Context, *connect.Request[v1.GetUserTagsRequest]) (*connect.Response[v1.GetUserTagsResponse], error)
	// CheckUserHasTag 检查用户是否有指定标签
	//
	// 通过标签代码（code）快速检查用户是否拥有该标签。
	CheckUserHasTag(context.Context, *connect.Request[v1.CheckUserHasTagRequest]) (*connect.Response[v1.CheckUserHasTagResponse], error)
	// GetRecentAnnouncements 获取最近公告列表
	//
	// 获取当前应用所属商户的最近公告（最多 10 条）。
	// 返回结果包含 MD5 和 SHA256 哈希值，客户端可用于判断是否需要重新展示。
	//
	// 使用场景：
	// - 客户端首次获取公告后，存储哈希值
	// - 后续请求时，对比哈希值是否变化
	// - 如果哈希值相同，说明公告无变化，可不展示
	// - 如果哈希值不同，说明公告有更新，需要展示
	GetRecentAnnouncements(context.Context, *connect.Request[v1.GetRecentAnnouncementsRequest]) (*connect.Response[v1.GetRecentAnnouncementsResponse], error)
	// GetAnnouncement 获取单个公告详情
	//
	// 根据公告 ID 获取详细信息。
	GetAnnouncement(context.Context, *connect.Request[v1.GetAnnouncementRequest]) (*connect.Response[v1.GetAnnouncementResponse], error)
}

// NewMerchantServiceClient constructs a client for the beacon.sso.v1.MerchantService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMerchantServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MerchantServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	merchantServiceMethods := v1.File_beacon_sso_v1_merchant_service_proto.Services().ByName("MerchantService").Methods()
	return &merchantServiceClient{
		getMerchantTags: connect.NewClient[v1.GetMerchantTagsRequest, v1.GetMerchantTagsResponse](
			httpClient,
			baseURL+MerchantServiceGetMerchantTagsProcedure,
			connect.WithSchema(merchantServiceMethods.ByName("GetMerchantTags")),
			connect.WithClientOptions(opts...),
		),
		getUserTags: connect.NewClient[v1.GetUserTagsRequest, v1.GetUserTagsResponse](
			httpClient,
			baseURL+MerchantServiceGetUserTagsProcedure,
			connect.WithSchema(merchantServiceMethods.ByName("GetUserTags")),
			connect.WithClientOptions(opts...),
		),
		checkUserHasTag: connect.NewClient[v1.CheckUserHasTagRequest, v1.CheckUserHasTagResponse](
			httpClient,
			baseURL+MerchantServiceCheckUserHasTagProcedure,
			connect.WithSchema(merchantServiceMethods.ByName("CheckUserHasTag")),
			connect.WithClientOptions(opts...),
		),
		getRecentAnnouncements: connect.NewClient[v1.GetRecentAnnouncementsRequest, v1.GetRecentAnnouncementsResponse](
			httpClient,
			baseURL+MerchantServiceGetRecentAnnouncementsProcedure,
			connect.WithSchema(merchantServiceMethods.ByName("GetRecentAnnouncements")),
			connect.WithClientOptions(opts...),
		),
		getAnnouncement: connect.NewClient[v1.GetAnnouncementRequest, v1.GetAnnouncementResponse](
			httpClient,
			baseURL+MerchantServiceGetAnnouncementProcedure,
			connect.WithSchema(merchantServiceMethods.ByName("GetAnnouncement")),
			connect.WithClientOptions(opts...),
		),
	}
}

// merchantServiceClient implements MerchantServiceClient.
type merchantServiceClient struct {
	getMerchantTags        *connect.Client[v1.GetMerchantTagsRequest, v1.GetMerchantTagsResponse]
	getUserTags            *connect.Client[v1.GetUserTagsRequest, v1.GetUserTagsResponse]
	checkUserHasTag        *connect.Client[v1.CheckUserHasTagRequest, v1.CheckUserHasTagResponse]
	getRecentAnnouncements *connect.Client[v1.GetRecentAnnouncementsRequest, v1.GetRecentAnnouncementsResponse]
	getAnnouncement        *connect.Client[v1.GetAnnouncementRequest, v1.GetAnnouncementResponse]
}

// GetMerchantTags calls beacon.sso.v1.MerchantService.GetMerchantTags.
func (c *merchantServiceClient) GetMerchantTags(ctx context.Context, req *connect.Request[v1.GetMerchantTagsRequest]) (*connect.Response[v1.GetMerchantTagsResponse], error) {
	return c.getMerchantTags.CallUnary(ctx, req)
}

// GetUserTags calls beacon.sso.v1.MerchantService.GetUserTags.
func (c *merchantServiceClient) GetUserTags(ctx context.Context, req *connect.Request[v1.GetUserTagsRequest]) (*connect.Response[v1.GetUserTagsResponse], error) {
	return c.getUserTags.CallUnary(ctx, req)
}

// CheckUserHasTag calls beacon.sso.v1.MerchantService.CheckUserHasTag.
func (c *merchantServiceClient) CheckUserHasTag(ctx context.Context, req *connect.Request[v1.CheckUserHasTagRequest]) (*connect.Response[v1.CheckUserHasTagResponse], error) {
	return c.checkUserHasTag.CallUnary(ctx, req)
}

// GetRecentAnnouncements calls beacon.sso.v1.MerchantService.GetRecentAnnouncements.
func (c *merchantServiceClient) GetRecentAnnouncements(ctx context.Context, req *connect.Request[v1.GetRecentAnnouncementsRequest]) (*connect.Response[v1.GetRecentAnnouncementsResponse], error) {
	return c.getRecentAnnouncements.CallUnary(ctx, req)
}

// GetAnnouncement calls beacon.sso.v1.MerchantService.GetAnnouncement.
func (c *merchantServiceClient) GetAnnouncement(ctx context.Context, req *connect.Request[v1.GetAnnouncementRequest]) (*connect.Response[v1.GetAnnouncementResponse], error) {
	return c.getAnnouncement.CallUnary(ctx, req)
}

// MerchantServiceHandler is an implementation of the beacon.sso.v1.MerchantService service.
type MerchantServiceHandler interface {
	// GetMerchantTags 获取当前应用所属商户的所有标签
	//
	// 返回应用所属商户下的所有标签列表，可用于客户端展示或标签匹配。
	GetMerchantTags(context.Context, *connect.Request[v1.GetMerchantTagsRequest]) (*connect.Response[v1.GetMerchantTagsResponse], error)
	// GetUserTags 获取指定用户在当前商户的所有标签
	//
	// 根据用户 ID 获取该用户在当前应用所属商户下的所有标签。
	GetUserTags(context.Context, *connect.Request[v1.GetUserTagsRequest]) (*connect.Response[v1.GetUserTagsResponse], error)
	// CheckUserHasTag 检查用户是否有指定标签
	//
	// 通过标签代码（code）快速检查用户是否拥有该标签。
	CheckUserHasTag(context.Context, *connect.Request[v1.CheckUserHasTagRequest]) (*connect.Response[v1.CheckUserHasTagResponse], error)
	// GetRecentAnnouncements 获取最近公告列表
	//
	// 获取当前应用所属商户的最近公告（最多 10 条）。
	// 返回结果包含 MD5 和 SHA256 哈希值，客户端可用于判断是否需要重新展示。
	//
	// 使用场景：
	// - 客户端首次获取公告后，存储哈希值
	// - 后续请求时，对比哈希值是否变化
	// - 如果哈希值相同，说明公告无变化，可不展示
	// - 如果哈希值不同，说明公告有更新，需要展示
	GetRecentAnnouncements(context.Context, *connect.Request[v1.GetRecentAnnouncementsRequest]) (*connect.Response[v1.GetRecentAnnouncementsResponse], error)
	// GetAnnouncement 获取单个公告详情
	//
	// 根据公告 ID 获取详细信息。
	GetAnnouncement(context.Context, *connect.Request[v1.GetAnnouncementRequest]) (*connect.Response[v1.GetAnnouncementResponse], error)
}

// NewMerchantServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMerchantServiceHandler(svc MerchantServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	merchantServiceMethods := v1.File_beacon_sso_v1_merchant_service_proto.Services().ByName("MerchantService").Methods()
	merchantServiceGetMerchantTagsHandler := connect.NewUnaryHandler(
		MerchantServiceGetMerchantTagsProcedure,
		svc.GetMerchantTags,
		connect.WithSchema(merchantServiceMethods.ByName("GetMerchantTags")),
		connect.WithHandlerOptions(opts...),
	)
	merchantServiceGetUserTagsHandler := connect.NewUnaryHandler(
		MerchantServiceGetUserTagsProcedure,
		svc.GetUserTags,
		connect.WithSchema(merchantServiceMethods.ByName("GetUserTags")),
		connect.WithHandlerOptions(opts...),
	)
	merchantServiceCheckUserHasTagHandler := connect.NewUnaryHandler(
		MerchantServiceCheckUserHasTagProcedure,
		svc.CheckUserHasTag,
		connect.WithSchema(merchantServiceMethods.ByName("CheckUserHasTag")),
		connect.WithHandlerOptions(opts...),
	)
	merchantServiceGetRecentAnnouncementsHandler := connect.NewUnaryHandler(
		MerchantServiceGetRecentAnnouncementsProcedure,
		svc.GetRecentAnnouncements,
		connect.WithSchema(merchantServiceMethods.ByName("GetRecentAnnouncements")),
		connect.WithHandlerOptions(opts...),
	)
	merchantServiceGetAnnouncementHandler := connect.NewUnaryHandler(
		MerchantServiceGetAnnouncementProcedure,
		svc.GetAnnouncement,
		connect.WithSchema(merchantServiceMethods.ByName("GetAnnouncement")),
		connect.WithHandlerOptions(opts...),
	)
	return "/beacon.sso.v1.MerchantService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MerchantServiceGetMerchantTagsProcedure:
			merchantServiceGetMerchantTagsHandler.ServeHTTP(w, r)
		case MerchantServiceGetUserTagsProcedure:
			merchantServiceGetUserTagsHandler.ServeHTTP(w, r)
		case MerchantServiceCheckUserHasTagProcedure:
			merchantServiceCheckUserHasTagHandler.ServeHTTP(w, r)
		case MerchantServiceGetRecentAnnouncementsProcedure:
			merchantServiceGetRecentAnnouncementsHandler.ServeHTTP(w, r)
		case MerchantServiceGetAnnouncementProcedure:
			merchantServiceGetAnnouncementHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMerchantServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedMerchantServiceHandler struct{}

func (UnimplementedMerchantServiceHandler) GetMerchantTags(context.Context, *connect.Request[v1.GetMerchantTagsRequest]) (*connect.Response[v1.GetMerchantTagsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("beacon.sso.v1.MerchantService.GetMerchantTags is not implemented"))
}

func (UnimplementedMerchantServiceHandler) GetUserTags(context.Context, *connect.Request[v1.GetUserTagsRequest]) (*connect.Response[v1.GetUserTagsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("beacon.sso.v1.MerchantService.GetUserTags is not implemented"))
}

func (UnimplementedMerchantServiceHandler) CheckUserHasTag(context.Context, *connect.Request[v1.CheckUserHasTagRequest]) (*connect.Response[v1.CheckUserHasTagResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("beacon.sso.v1.MerchantService.CheckUserHasTag is not implemented"))
}

func (UnimplementedMerchantServiceHandler) GetRecentAnnouncements(context.Context, *connect.Request[v1.GetRecentAnnouncementsRequest]) (*connect.Response[v1.GetRecentAnnouncementsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("beacon.sso.v1.MerchantService.GetRecentAnnouncements is not implemented"))
}

func (UnimplementedMerchantServiceHandler) GetAnnouncement(context.Context, *connect.Request[v1.GetAnnouncementRequest]) (*connect.Response[v1.GetAnnouncementResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("beacon.sso.v1.MerchantService.GetAnnouncement is not implemented"))
}
