// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: beacon/sso/v1/public.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/phalanx-labs/beacon-sso-sdk/client/api/beacon/sso/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PublicServiceName is the fully-qualified name of the PublicService service.
	PublicServiceName = "beacon.sso.v1.PublicService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PublicServiceSendRegisterEmailCodeProcedure is the fully-qualified name of the PublicService's
	// SendRegisterEmailCode RPC.
	PublicServiceSendRegisterEmailCodeProcedure = "/beacon.sso.v1.PublicService/SendRegisterEmailCode"
)

// PublicServiceClient is a client for the beacon.sso.v1.PublicService service.
type PublicServiceClient interface {
	// SendRegisterEmailCode 发送注册邮箱验证码
	//
	// 该接口用于向指定邮箱发送注册验证码，验证码有效期为环境变量 EMAIL_VERIFY_CODE_EXPIRE 配置的时间（默认 15 分钟）。
	// 同一邮箱在 1 分钟内只能发送一次验证码。
	SendRegisterEmailCode(context.Context, *connect.Request[v1.SendRegisterEmailCodeRequest]) (*connect.Response[v1.SendRegisterEmailCodeResponse], error)
}

// NewPublicServiceClient constructs a client for the beacon.sso.v1.PublicService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPublicServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PublicServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	publicServiceMethods := v1.File_beacon_sso_v1_public_proto.Services().ByName("PublicService").Methods()
	return &publicServiceClient{
		sendRegisterEmailCode: connect.NewClient[v1.SendRegisterEmailCodeRequest, v1.SendRegisterEmailCodeResponse](
			httpClient,
			baseURL+PublicServiceSendRegisterEmailCodeProcedure,
			connect.WithSchema(publicServiceMethods.ByName("SendRegisterEmailCode")),
			connect.WithClientOptions(opts...),
		),
	}
}

// publicServiceClient implements PublicServiceClient.
type publicServiceClient struct {
	sendRegisterEmailCode *connect.Client[v1.SendRegisterEmailCodeRequest, v1.SendRegisterEmailCodeResponse]
}

// SendRegisterEmailCode calls beacon.sso.v1.PublicService.SendRegisterEmailCode.
func (c *publicServiceClient) SendRegisterEmailCode(ctx context.Context, req *connect.Request[v1.SendRegisterEmailCodeRequest]) (*connect.Response[v1.SendRegisterEmailCodeResponse], error) {
	return c.sendRegisterEmailCode.CallUnary(ctx, req)
}

// PublicServiceHandler is an implementation of the beacon.sso.v1.PublicService service.
type PublicServiceHandler interface {
	// SendRegisterEmailCode 发送注册邮箱验证码
	//
	// 该接口用于向指定邮箱发送注册验证码，验证码有效期为环境变量 EMAIL_VERIFY_CODE_EXPIRE 配置的时间（默认 15 分钟）。
	// 同一邮箱在 1 分钟内只能发送一次验证码。
	SendRegisterEmailCode(context.Context, *connect.Request[v1.SendRegisterEmailCodeRequest]) (*connect.Response[v1.SendRegisterEmailCodeResponse], error)
}

// NewPublicServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPublicServiceHandler(svc PublicServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	publicServiceMethods := v1.File_beacon_sso_v1_public_proto.Services().ByName("PublicService").Methods()
	publicServiceSendRegisterEmailCodeHandler := connect.NewUnaryHandler(
		PublicServiceSendRegisterEmailCodeProcedure,
		svc.SendRegisterEmailCode,
		connect.WithSchema(publicServiceMethods.ByName("SendRegisterEmailCode")),
		connect.WithHandlerOptions(opts...),
	)
	return "/beacon.sso.v1.PublicService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PublicServiceSendRegisterEmailCodeProcedure:
			publicServiceSendRegisterEmailCodeHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPublicServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPublicServiceHandler struct{}

func (UnimplementedPublicServiceHandler) SendRegisterEmailCode(context.Context, *connect.Request[v1.SendRegisterEmailCodeRequest]) (*connect.Response[v1.SendRegisterEmailCodeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("beacon.sso.v1.PublicService.SendRegisterEmailCode is not implemented"))
}
